{
  imports = [
    ./adblock.nix
    ./atuin.nix
    ./coreutils.nix
    ./docker.nix
    ./emacs.nix
    ./fonts.nix
    ./git.nix
    ./homebrew.nix
    ./keyboard.nix
    ./macos.nix
    ./slack.nix
    ./spotify.nix
    ./starship.nix
    ./utm.nix
    ./whatsapp.nix
    ./wireguard.nix
    ./zoom.nix
    ./zsh.nix
  ];
}
