{
  imports = [
    ./atuin.nix
    ./aspell.nix
    #./coreutils.nix
    ./direnv.nix
    ./emacs.nix
    ./fonts.nix
    ./git.nix
    ./gnumake.nix
    ./gnupg.nix
    ./gnuplot.nix
    ./nixd.nix
    ./notmuch.nix
    ./ripgrep.nix
    ./starship.nix
    ./uutils.nix
    ./zsh-completions.nix
    ./zsh.nix
  ];
}
