repos:
- repo: local
  hooks:
    - id: nixfmt
      name: run nixfmt
      language: system
      entry: nixfmt
      files: \.nix$
- repo: local
  hooks:
    - id: statix
      name: run statix
      language: system
      entry: statix check --format errfmt
      files: \.nix$
