name: Generate Markdown

on:
  push:
    branches: [ "readme" ]

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: purcell/setup-emacs@master
        with:
          version: 28.2
      - run: ./script/generate-markdown
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Regenerate nix.md
